require('node:fs').mkdirSync('tests/results',{recursive:true});
const TEST_URL=process.env.CYOA_TEST_URL||'http://127.0.0.1:5697';
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://api.github.com/**',r=>r.fulfill({status:404,body:'{}'}));
await page.addInitScript(()=>{
 const project={id:'11111111-1111-4111-8111-111111111111',name:'Gaston: Naruto',title:'Naruto',author:'Gaston',fandom:'Naruto',completion:'Complete',is_mod:true,build_count:2,description:'',cover_image:null,file_path:'/fixture/project.json',viewer_preference:'icc2-plus',favorite:false,exclude_from_perk_index:false,date_added:'2026-10-07',tags:['Adventure'],file_missing:false};
 const version={id:'33333333-3333-4333-8333-333333333333',created_at:'2026-10-07',reason:'Before update',starred:false,project};let projects=[project];window.__calls=[];
 window.__TAURI_INTERNALS__={transformCallback:()=>1,unregisterCallback:()=>{},invoke:async(command,args)=>{window.__calls.push({command,args});
 if(command==='get_library')return projects;if(command==='get_viewers')return [{id:'icc2-plus',name:'ICC2 Plus'},{id:'icc-original',name:'ICC Original'}];if(command==='list_versions'||command==='list_archives')return [version];if(command==='get_fonts')return ['system-ui','DejaVu Sans'];if(command==='load_preferences')return {theme:'mocha',managerFont:'system-ui',cyoaFont:'',archiveLimit:5};if(command==='archive_version')projects=[];if(command==='restore_version')projects=[project];if(command==='find_duplicates')return [];return null;}};
});
await page.goto(TEST_URL+'/#/settings');for(const [theme,color]of [['latte','rgb(239, 241, 245)'],['frappe','rgb(48, 52, 70)'],['macchiato','rgb(36, 39, 58)'],['mocha','rgb(30, 30, 46)']]){await page.locator('select').filter({has:page.locator('option[value=mocha]')}).selectOption(theme);assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),color);}
await page.waitForTimeout(200);await page.screenshot({path:'tests/results/settings.png'});
await page.goto(TEST_URL+'/#/');await page.getByTitle('Options').first().click();const popup=page.getByRole('menuitem',{name:'Version history',exact:true});await popup.waitFor();assert(await popup.evaluate(e=>{const r=e.getBoundingClientRect();return r.bottom<=innerHeight&&r.left>=0}));await popup.click();await page.getByRole('button',{name:'Open archive',exact:true}).click();await page.getByRole('button',{name:'☆ Keep forever',exact:true}).click();await page.getByRole('button',{name:'Move current edition to archive',exact:true}).click();await page.getByRole('button',{name:'Restore to library',exact:true}).click();await page.screenshot({path:'tests/results/history.png'});const calls=await page.evaluate(()=>window.__calls.map(c=>c.command));for(const c of ['star_version','open_viewer_window','archive_version','restore_version'])assert(calls.includes(c),c);assert.deepEqual(errors,[]);await browser.close();console.log('Manager UI passed: four palettes, unclipped menu, direct archive opening, starring, move and restore. Backend mocked.');})().catch(e=>{console.error(e);process.exit(1)});
